export default {
    200: { text: 'thunderstorm with light rain', icon: '11d' },
    201: { text: 'thunderstorm with rain', icon: '11d' },
    202: { text: 'thunderstorm with heavy rain', icon: '11d' },
    210: { text: 'light thunderstorm', icon: '11d' },
    211: { text: 'thunderstorm', icon: '11d' },
    212: { text: 'heavy thunderstorm', icon: '11d' },
    221: { text: 'ragged thunderstorm', icon: '11d' },
    230: { text: 'thunderstorm with light drizzle', icon: '11d' },
    231: { text: 'thunderstorm with drizzle', icon: '11d' },
    232: { text: 'thunderstorm with heavy drizzle', icon: '11d' },
    300: { text: 'light intensity drizzle', icon: '09d' },
    301: { text: 'drizzle', icon: '09d' },
    302: { text: 'heavy intensity drizzle', icon: '09d' },
    310: { text: 'light intensity drizzle rain', icon: '09d' },
    311: { text: 'drizzle rain', icon: '09d' },
    312: { text: 'heavy intensity drizzle rain', icon: '09d' },
    313: { text: 'shower rain and drizzle', icon: '09d' },
    314: { text: 'heavy shower rain and drizzle', icon: '09d' },
    321: { text: 'shower drizzle', icon: '09d' },
    500: { text: 'light rain', icon: '10d' },
    501: { text: 'moderate rain', icon: '10d' },
    502: { text: 'heavy intensity rain', icon: '10d' },
    503: { text: 'very heavy rain', icon: '10d' },
    504: { text: 'extreme rain', icon: '10d' },
    511: { text: 'freezing rain', icon: '13d' },
    520: { text: 'light intensity shower rain', icon: '09d' },
    521: { text: 'shower rain', icon: '09d' },
    522: { text: 'heavy intensity shower rain', icon: '09d' },
    531: { text: 'ragged shower rain', icon: '09d' },
    600: { text: 'light snow', icon: '13d' },
    601: { text: 'snow', icon: '13d' },
    602: { text: 'heavy snow', icon: '13d' },
    611: { text: 'sleet', icon: '13d' },
    612: { text: 'shower sleet', icon: '13d' },
    615: { text: 'light rain and snow', icon: '13d' },
    616: { text: 'rain and snow', icon: '13d' },
    620: { text: 'light shower snow', icon: '13d' },
    621: { text: 'shower snow', icon: '13d' },
    622: { text: 'heavy shower snow', icon: '13d' },
    701: { text: 'mist', icon: '50d' },
    711: { text: 'smoke', icon: '50d' },
    721: { text: 'haze', icon: '50d' },
    731: { text: 'sand, dust whirls', icon: '50d' },
    741: { text: 'fog', icon: '50d' },
    751: { text: 'sand', icon: '50d' },
    761: { text: 'dust', icon: '50d' },
    762: { text: 'volcanic ash', icon: '50d' },
    771: { text: 'squalls', icon: '50d' },
    781: { text: 'tornado', icon: '50d' },
    800: { text: 'clear sky 01d', icon: '01n' },
    801: { text: 'few clouds 02d', icon: '02n' },
    802: { text: 'scattered clouds 03d', icon: '03n' },
    803: { text: 'broken clouds 04d', icon: '04n' },
    804: { text: 'overcast clouds 04d', icon: '04n' },
    900: { text: 'tornado' },
    901: { text: 'tropical storm' },
    902: { text: 'hurricane' },
    903: { text: 'cold' },
    904: { text: 'hot' },
    905: { text: 'windy' },
    906: { text: 'hail' },
    951: { text: 'calm' },
    952: { text: 'light breeze' },
    953: { text: 'gentle breeze' },
    954: { text: 'moderate breeze' },
    955: { text: 'fresh breeze' },
    956: { text: 'strong breeze' },
    957: { text: 'high wind, near gale' },
    958: { text: 'gale' },
    959: { text: 'severe gale' },
    960: { text: 'storm' },
    961: { text: 'violent storm' },
    962: { text: 'hurricane ' },
}
